# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /ljrServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /ljrServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /ljrServer/CMakeFiles /ljrServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /ljrServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named ljrServer

# Build rule for target.
ljrServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ljrServer
.PHONY : ljrServer

# fast build rule for target.
ljrServer/fast:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/build
.PHONY : ljrServer/fast

ljrServer/config.o: ljrServer/config.cpp.o

.PHONY : ljrServer/config.o

# target to build an object file
ljrServer/config.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/config.cpp.o
.PHONY : ljrServer/config.cpp.o

ljrServer/config.i: ljrServer/config.cpp.i

.PHONY : ljrServer/config.i

# target to preprocess a source file
ljrServer/config.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/config.cpp.i
.PHONY : ljrServer/config.cpp.i

ljrServer/config.s: ljrServer/config.cpp.s

.PHONY : ljrServer/config.s

# target to generate assembly for a file
ljrServer/config.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/config.cpp.s
.PHONY : ljrServer/config.cpp.s

ljrServer/fd_manager.o: ljrServer/fd_manager.cpp.o

.PHONY : ljrServer/fd_manager.o

# target to build an object file
ljrServer/fd_manager.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fd_manager.cpp.o
.PHONY : ljrServer/fd_manager.cpp.o

ljrServer/fd_manager.i: ljrServer/fd_manager.cpp.i

.PHONY : ljrServer/fd_manager.i

# target to preprocess a source file
ljrServer/fd_manager.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fd_manager.cpp.i
.PHONY : ljrServer/fd_manager.cpp.i

ljrServer/fd_manager.s: ljrServer/fd_manager.cpp.s

.PHONY : ljrServer/fd_manager.s

# target to generate assembly for a file
ljrServer/fd_manager.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fd_manager.cpp.s
.PHONY : ljrServer/fd_manager.cpp.s

ljrServer/fiber.o: ljrServer/fiber.cpp.o

.PHONY : ljrServer/fiber.o

# target to build an object file
ljrServer/fiber.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fiber.cpp.o
.PHONY : ljrServer/fiber.cpp.o

ljrServer/fiber.i: ljrServer/fiber.cpp.i

.PHONY : ljrServer/fiber.i

# target to preprocess a source file
ljrServer/fiber.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fiber.cpp.i
.PHONY : ljrServer/fiber.cpp.i

ljrServer/fiber.s: ljrServer/fiber.cpp.s

.PHONY : ljrServer/fiber.s

# target to generate assembly for a file
ljrServer/fiber.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/fiber.cpp.s
.PHONY : ljrServer/fiber.cpp.s

ljrServer/hook.o: ljrServer/hook.cpp.o

.PHONY : ljrServer/hook.o

# target to build an object file
ljrServer/hook.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/hook.cpp.o
.PHONY : ljrServer/hook.cpp.o

ljrServer/hook.i: ljrServer/hook.cpp.i

.PHONY : ljrServer/hook.i

# target to preprocess a source file
ljrServer/hook.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/hook.cpp.i
.PHONY : ljrServer/hook.cpp.i

ljrServer/hook.s: ljrServer/hook.cpp.s

.PHONY : ljrServer/hook.s

# target to generate assembly for a file
ljrServer/hook.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/hook.cpp.s
.PHONY : ljrServer/hook.cpp.s

ljrServer/iomanager.o: ljrServer/iomanager.cpp.o

.PHONY : ljrServer/iomanager.o

# target to build an object file
ljrServer/iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/iomanager.cpp.o
.PHONY : ljrServer/iomanager.cpp.o

ljrServer/iomanager.i: ljrServer/iomanager.cpp.i

.PHONY : ljrServer/iomanager.i

# target to preprocess a source file
ljrServer/iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/iomanager.cpp.i
.PHONY : ljrServer/iomanager.cpp.i

ljrServer/iomanager.s: ljrServer/iomanager.cpp.s

.PHONY : ljrServer/iomanager.s

# target to generate assembly for a file
ljrServer/iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/iomanager.cpp.s
.PHONY : ljrServer/iomanager.cpp.s

ljrServer/log.o: ljrServer/log.cpp.o

.PHONY : ljrServer/log.o

# target to build an object file
ljrServer/log.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/log.cpp.o
.PHONY : ljrServer/log.cpp.o

ljrServer/log.i: ljrServer/log.cpp.i

.PHONY : ljrServer/log.i

# target to preprocess a source file
ljrServer/log.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/log.cpp.i
.PHONY : ljrServer/log.cpp.i

ljrServer/log.s: ljrServer/log.cpp.s

.PHONY : ljrServer/log.s

# target to generate assembly for a file
ljrServer/log.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/log.cpp.s
.PHONY : ljrServer/log.cpp.s

ljrServer/scheduler.o: ljrServer/scheduler.cpp.o

.PHONY : ljrServer/scheduler.o

# target to build an object file
ljrServer/scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/scheduler.cpp.o
.PHONY : ljrServer/scheduler.cpp.o

ljrServer/scheduler.i: ljrServer/scheduler.cpp.i

.PHONY : ljrServer/scheduler.i

# target to preprocess a source file
ljrServer/scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/scheduler.cpp.i
.PHONY : ljrServer/scheduler.cpp.i

ljrServer/scheduler.s: ljrServer/scheduler.cpp.s

.PHONY : ljrServer/scheduler.s

# target to generate assembly for a file
ljrServer/scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/scheduler.cpp.s
.PHONY : ljrServer/scheduler.cpp.s

ljrServer/thread.o: ljrServer/thread.cpp.o

.PHONY : ljrServer/thread.o

# target to build an object file
ljrServer/thread.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/thread.cpp.o
.PHONY : ljrServer/thread.cpp.o

ljrServer/thread.i: ljrServer/thread.cpp.i

.PHONY : ljrServer/thread.i

# target to preprocess a source file
ljrServer/thread.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/thread.cpp.i
.PHONY : ljrServer/thread.cpp.i

ljrServer/thread.s: ljrServer/thread.cpp.s

.PHONY : ljrServer/thread.s

# target to generate assembly for a file
ljrServer/thread.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/thread.cpp.s
.PHONY : ljrServer/thread.cpp.s

ljrServer/timer.o: ljrServer/timer.cpp.o

.PHONY : ljrServer/timer.o

# target to build an object file
ljrServer/timer.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/timer.cpp.o
.PHONY : ljrServer/timer.cpp.o

ljrServer/timer.i: ljrServer/timer.cpp.i

.PHONY : ljrServer/timer.i

# target to preprocess a source file
ljrServer/timer.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/timer.cpp.i
.PHONY : ljrServer/timer.cpp.i

ljrServer/timer.s: ljrServer/timer.cpp.s

.PHONY : ljrServer/timer.s

# target to generate assembly for a file
ljrServer/timer.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/timer.cpp.s
.PHONY : ljrServer/timer.cpp.s

ljrServer/util.o: ljrServer/util.cpp.o

.PHONY : ljrServer/util.o

# target to build an object file
ljrServer/util.cpp.o:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/util.cpp.o
.PHONY : ljrServer/util.cpp.o

ljrServer/util.i: ljrServer/util.cpp.i

.PHONY : ljrServer/util.i

# target to preprocess a source file
ljrServer/util.cpp.i:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/util.cpp.i
.PHONY : ljrServer/util.cpp.i

ljrServer/util.s: ljrServer/util.cpp.s

.PHONY : ljrServer/util.s

# target to generate assembly for a file
ljrServer/util.cpp.s:
	$(MAKE) -f CMakeFiles/ljrServer.dir/build.make CMakeFiles/ljrServer.dir/ljrServer/util.cpp.s
.PHONY : ljrServer/util.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

tests/test_config.o: tests/test_config.cpp.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.o
.PHONY : tests/test_config.cpp.o

tests/test_config.i: tests/test_config.cpp.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.i
.PHONY : tests/test_config.cpp.i

tests/test_config.s: tests/test_config.cpp.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.s
.PHONY : tests/test_config.cpp.s

tests/test_fiber.o: tests/test_fiber.cpp.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cpp.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.cpp.o

tests/test_fiber.i: tests/test_fiber.cpp.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cpp.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.cpp.i

tests/test_fiber.s: tests/test_fiber.cpp.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cpp.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.cpp.s

tests/test_hook.o: tests/test_hook.cpp.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cpp.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.o
.PHONY : tests/test_hook.cpp.o

tests/test_hook.i: tests/test_hook.cpp.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cpp.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.i
.PHONY : tests/test_hook.cpp.i

tests/test_hook.s: tests/test_hook.cpp.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cpp.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.s
.PHONY : tests/test_hook.cpp.s

tests/test_iomanager.o: tests/test_iomanager.cpp.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cpp.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.cpp.o

tests/test_iomanager.i: tests/test_iomanager.cpp.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cpp.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.cpp.i

tests/test_iomanager.s: tests/test_iomanager.cpp.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cpp.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.cpp.s

tests/test_scheduler.o: tests/test_scheduler.cpp.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.cpp.o

tests/test_scheduler.i: tests/test_scheduler.cpp.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.cpp.i

tests/test_scheduler.s: tests/test_scheduler.cpp.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.cpp.s

tests/test_thread.o: tests/test_thread.cpp.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cpp.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.o
.PHONY : tests/test_thread.cpp.o

tests/test_thread.i: tests/test_thread.cpp.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cpp.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.i
.PHONY : tests/test_thread.cpp.i

tests/test_thread.s: tests/test_thread.cpp.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cpp.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.s
.PHONY : tests/test_thread.cpp.s

tests/test_util.o: tests/test_util.cpp.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cpp.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.o
.PHONY : tests/test_util.cpp.o

tests/test_util.i: tests/test_util.cpp.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cpp.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.i
.PHONY : tests/test_util.cpp.i

tests/test_util.s: tests/test_util.cpp.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cpp.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.s
.PHONY : tests/test_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_hook"
	@echo "... test_iomanager"
	@echo "... test_scheduler"
	@echo "... test_fiber"
	@echo "... rebuild_cache"
	@echo "... test_util"
	@echo "... test_config"
	@echo "... edit_cache"
	@echo "... test_thread"
	@echo "... test"
	@echo "... ljrServer"
	@echo "... ljrServer/config.o"
	@echo "... ljrServer/config.i"
	@echo "... ljrServer/config.s"
	@echo "... ljrServer/fd_manager.o"
	@echo "... ljrServer/fd_manager.i"
	@echo "... ljrServer/fd_manager.s"
	@echo "... ljrServer/fiber.o"
	@echo "... ljrServer/fiber.i"
	@echo "... ljrServer/fiber.s"
	@echo "... ljrServer/hook.o"
	@echo "... ljrServer/hook.i"
	@echo "... ljrServer/hook.s"
	@echo "... ljrServer/iomanager.o"
	@echo "... ljrServer/iomanager.i"
	@echo "... ljrServer/iomanager.s"
	@echo "... ljrServer/log.o"
	@echo "... ljrServer/log.i"
	@echo "... ljrServer/log.s"
	@echo "... ljrServer/scheduler.o"
	@echo "... ljrServer/scheduler.i"
	@echo "... ljrServer/scheduler.s"
	@echo "... ljrServer/thread.o"
	@echo "... ljrServer/thread.i"
	@echo "... ljrServer/thread.s"
	@echo "... ljrServer/timer.o"
	@echo "... ljrServer/timer.i"
	@echo "... ljrServer/timer.s"
	@echo "... ljrServer/util.o"
	@echo "... ljrServer/util.i"
	@echo "... ljrServer/util.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

